Copyright = "Jeffrey Phillips Freeman 2023 - present"

paginate = 20
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsStyle = "monokai"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

enableRobotsTXT = true

[services.rss]
limit = 50

[permalinks]
post = "/:title/"

[taxonimies]
tag = "tags"

[mediaTypes]
[mediaTypes."text/javascript"]
suffixes = ["js", "mjs"]
[mediaTypes."application/activity+json"]
suffixes = ["ajson"]
[mediaTypes."application/json"]
suffixes = ["json"]

[outputFormats]
[outputFormats.ACTIVITY]
mediaType = "application/activity+json"
notAlternative = true
baseName = "activity"
[outputFormats.ACTIVITY_OUTBOX]
mediaType = "application/activity+json"
notAlternative = true
baseName = "outbox"
[outputFormats.MANIFEST]
mediaType = "application/json"
notAlternative = true
baseName = "manifest"

[outputs]
home = ["HTML", "RSS", "ACTIVITY", "ACTIVITY_OUTBOX", "MANIFEST"]
section = ["HTML", "RSS"]
page = ["HTML"]

[related]
# Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
threshold = 10

# To get stable "See also" sections we, by default, exclude newer related pages.
includeNewer = true

# Will lower case keywords in both queries and in the indexes.
toLower = false

[[related.indices]]
name = "tags"
weight = 100

[markup.goldmark.parser]
autoHeadingID = true

[markup.goldmark.extensions]
typographer = false

[markup.goldmark.renderer]
unsafe = true

[security.funcs]
getenv = ['^HUGO_', '^CI$']

[params]
siteAuthor="Jeffrey Phillips Freeman"

[sitemap]
filename = 'sitemap.xml'
