default:
  image: node:18.17.1

deploy_preview:
  stage: deploy
  except:
    - master
    - develop
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=preview --token="${VERCEL_TOKEN}" -S "${VERCEL_SCOPE}"
    - vercel build --token="${VERCEL_TOKEN}" -S "${VERCEL_SCOPE}"
    - vercel deploy --prebuilt  --token="${VERCEL_TOKEN}" -S "${VERCEL_SCOPE}"

deploy_development:
  stage: deploy
  only:
    - develop
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=development --token="${VERCEL_TOKEN}" -S "${VERCEL_SCOPE}"
    - vercel build --token="${VERCEL_TOKEN}" -S "${VERCEL_SCOPE}"
    - vercel deploy --prebuilt  --token="${VERCEL_TOKEN}" -S "${VERCEL_SCOPE}"

deploy_production:
  stage: deploy
  only:
    - master
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=production --token="${VERCEL_TOKEN}" -S "${VERCEL_SCOPE}"
    - vercel build --prod --token="${VERCEL_TOKEN}" -S "${VERCEL_SCOPE}"
    - vercel deploy --prebuilt --prod --token="${VERCEL_TOKEN}" -S "${VERCEL_SCOPE}"
